
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: postgres -c max_connections=150
    networks:
      - ecommerce
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ecommerce
  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ecommerce
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ecommerce
  backend:
    image: creepereye/ecommerce-backend:${APP_IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecommerce
      DB_USERNAME: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: d3CUfHEIRFv/e3XvZe8XlEQLSZY3hOkb017Cjq13v7E=
      JWT_ACCESS_TOKEN_VALIDITY: 3600
      JWT_REFRESH_TOKEN_VALIDITY: 86400
      SPRING_APPLICATION_NAME: backend

    volumes:
      - /home/smalllab/Docker/ecommerce/nginx/images:/app/images

    networks:
      - ecommerce
    depends_on:
      - postgres
      - redis

    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 5s
        max_failure_ratio: 0.2
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  postgres_data:
networks:
  ecommerce:
    external: true

